version: '3.8'

services:
  internet-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eze-u-internet-monitor
    ports:
      - "8745:8745"
    volumes:
      # Persist SQLite database
      - ./backend/data:/app/backend/data
      # Optional: Mount monitoring.db directly for easy backup
      - ./backend/monitoring.db:/app/backend/monitoring.db
    environment:
      - NODE_ENV=production
      - PORT=8745
      - TZ=Africa/Johannesburg  # Set to your timezone
      # Phase 2/3: Better-sqlite3 and caching need more memory
      - NODE_OPTIONS=--max-old-space-size=768
    restart: unless-stopped
    networks:
      - monitor-network
    # Use host network mode for better ping/network access (optional)
    # network_mode: host  # Uncomment if you need direct host network access
    
    # Resource limits - UPDATED for Phase 2/3 optimizations (better-sqlite3, compression, caching)
    # Phase 2 adds: 64MB (sqlite3 cache) + Phase 3 adds: 10MB (query cache + compression buffers)
    # Recommended: 1GB memory, 2 CPUs for optimal performance
    deploy:
      resources:
        limits:
          cpus: '2.0'      # Increased from 1.0 (handles compression + database operations)
          memory: 1G       # Increased from 512M (accommodates caching + compression)
        reservations:
          cpus: '1.0'      # Increased from 0.5
          memory: 512M     # Increased from 256M
    
    # Alternative: Remove limits entirely for maximum performance
    # Comment out the deploy section above if you want unrestricted resources

networks:
  monitor-network:
    driver: bridge

volumes:
  monitor-data:
    driver: local
