version: '3.8'

services:
  internet-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eze-u-internet-monitor
    ports:
      - "8745:8745"
    volumes:
      # Persist SQLite database
      - ./backend/data:/app/backend/data
      # Optional: Mount monitoring.db directly for easy backup
      - ./backend/monitoring.db:/app/backend/monitoring.db
    environment:
      - NODE_ENV=production
      - PORT=8745
      - TZ=Africa/Johannesburg  # Set to your timezone
      # Phase 2/3: Better-sqlite3 and caching need more memory
      - NODE_OPTIONS=--max-old-space-size=768
    restart: unless-stopped
    
    # Resource limits using legacy format (compatible with Docker Compose 1.29.2)
    # Recommended: 1GB memory, 2 CPUs for optimal performance with Phase 2/3 optimizations
    mem_limit: 1g
    cpus: 2.0
    mem_reservation: 512m

networks:
  default:
    driver: bridge
